brainwave/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('post/', include('post.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .views import logout_view, delete_account
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    
    path('register/', views.signup, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', logout_view, name='logout'),
    path('delete/', delete_account, name='delete'),
    path('brainwave/', views.brainwave, name='brainwave'),
]

post/urls.py
from django.urls import path

from . import views
from .views import post_detail

app_name = 'post'

urlpatterns = [
    path('', views.posts, name='posts'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/', post_detail, name='post_detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:post_id>/like/', views.like_post, name='like_post'),
    path('comment/<int:comment_id>/like/', views.like_comment, name='like_comment'),
    path('comment/<int:pk>/delete/', views.delete_comment, name='delete_comment'),
]

post/models.py
from django.contrib.auth.models import User
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name

class Post(models.Model):
    titulo = models.CharField(max_length=50)
    texto = models.TextField(max_length=255, default='')
    created_by = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='post_likes', blank=True)
    
    def __str__(self):
        return self.titulo
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    texto = models.TextField()
    data_criacao = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='comment_likes', blank=True)

post/forms.py
from django import forms

from .models import Post, Comment

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('titulo', 'texto')
        widgets = {
            'titulo': forms.TextInput(attrs={
                'placeholder': 'Título',
                'class': INPUT_CLASSES
            }),
            'texto': forms.Textarea(attrs={
                'placeholder': 'Escreva sua publicação',
                'class': INPUT_CLASSES
            }),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['texto']
        widgets = {
            'texto': forms.Textarea(attrs={
                'placeholder': 'Escreva seu comentário',
                'class': INPUT_CLASSES
            }),
        }

class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('titulo', 'texto')
        widgets = {
            'titulo': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'texto': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            })
        }

post/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from .forms import NewPostForm, EditPostForm, CommentForm
from .models import Category, Post, Comment


def posts(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    posts = Post.objects.all()

    if category_id:
        posts = posts.filter(category_id=category_id)

    if query:
        posts = posts.filter(Q(titulo__icontains=query) | Q(texto__icontains=query))

    return render(request, 'post/posts.html', {
        'posts': posts,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })

def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = Comment.objects.filter(post=post)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.user = request.user  # ou qualquer método que você usa para obter o usuário atual
            comment.save()
    else:
        comment_form = CommentForm()

    return render(request, 'post_detail.html', {'post': post, 'comments': comments, 'comment_form': comment_form})

def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
    else:
        comment_form = CommentForm()

    comments = Comment.objects.filter(post=post)

    return render(request, 'post.html', {
        'post': post,
        'comments': comments,
        'comment_form': comment_form,
    })


@login_required
def new(request):
    if request.method == 'POST':
        form = NewPostForm(request.POST, request.FILES)

        if form.is_valid():
            post = form.save(commit=False)
            post.created_by = request.user
            post.save()

            return redirect('post:detail', pk=post.id)
    else:
        form = NewPostForm()

    return render(request, 'create_post.html', {
        'form': form,
        'title': 'New post',
    })

@login_required
def edit(request, pk):
    post = get_object_or_404(Post, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditPostForm(request.POST, request.FILES, instance=post)

        if form.is_valid():
            form.save()

            return redirect('post:detail', pk=post.id)
    else:
        form = EditPostForm(instance=post)

    return render(request, 'post.html', {
        'form': form,
        'title': 'Edit post',
    })

@login_required
def delete(request, pk):
    post = get_object_or_404(Post, pk=pk, created_by=request.user)

    if request.method == 'POST':
        post.delete()
        return redirect('core:brainwave')

    # Se o usuário não for o criador do post, levante uma exceção de permissão
    raise PermissionDenied

@login_required
def like_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    # Verifica se o usuário já curtiu o post
    liked = post.likes.filter(id=request.user.id).exists()

    if liked:
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)

    likes_count = post.likes.count()

    return JsonResponse({'liked': not liked, 'likes_count': likes_count})

@login_required
def like_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    # Verifica se o usuário já curtiu o comentário
    liked = comment.likes.filter(id=request.user.id).exists()

    if liked:
        comment.likes.remove(request.user)
    else:
        comment.likes.add(request.user)

    likes_count = comment.likes.count()

    return JsonResponse({'liked': not liked, 'likes_count': likes_count})

@login_required
def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)

    # Verifica se o usuário logado é o autor do comentário
    if request.user == comment.user:
        comment.delete()
        messages.success(request, 'Comentário excluído com sucesso.')
    else:
        messages.error(request, 'Você não tem permissão para excluir este comentário.')

    # Redireciona de volta à página do post ou para onde você desejar
    return redirect('post:detail', pk=comment.post.pk)

post/templates/create_post.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="stylesheet" href="{% static 'css/create_post.css' %}" /> {% static 'css/index.css' %}
        <link rel="stylesheet" href="{% static 'css/index.css' %}" />
        <link rel="stylesheet" href="{% static 'css/global.css' %}" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Arial:ital,wght@0,400;1,400&display=swap"/>
        <link rel="stylesheet"href="https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,400;0,700;1,400&display=swap"/>
        <title>{% block title %}Criar Post | Brainwave{% endblock %}</title>
    </head>

    <body>
        <div class = "body">
            <div>
                <img class = "onda_roxa" src="{% static 'images/onda-roxa@2x.png' %}" alt="">
                <img class = "mascote" src="{% static 'images/mascote@2x.png' %}" alt="">
                <img class = "logo" src="{% static 'images/logo@2x.png' %}" alt="">
                <em  class = "frase_efeito" >“Conectando mentes acadêmicas” - GRAN</em>
                <div class = "nome_empresa_1">Brainwave</div>
                <div class = "nome_empresa_2"><em>Network</em></div>

                
                <div class = "cabecalho">
                    <div class = "header_botao_1">
                        <a href="{% url 'core:brainwave' %}" style="text-decoration: none; color: inherit;"><img class = "home_icon"  src="{% static 'images/home@2x.png' %}" alt=""></a>
                        
                        <div style="align-self: center; margin-left: 10px;"><a href="{% url 'core:brainwave' %}" style="text-decoration: none; color: inherit;">Início</a></div>
                    </div>
                    <a href="{% url 'post:new' %}" style="text-decoration: none; color: inherit;"><div class = "header_botao_2"><div class = "simbolo_mais">+</div></div></a>

                    <div class="header_botao_3">
                        <div style="align-self: center; margin-right: 10px;">
                            {% if request.user.is_authenticated %} 
                                <div class="dropdown">
                                    <p href="javascript:void(0);" class="dropdown-toggle" style="text-decoration: none; margin-top: 20px;">{{ request.user.username }}</p>
                                    <div class="dropdown-menu">
                                        <a href="{% url 'core:logout' %}" style="text-decoration: none;">Sair</a>
                                        <a href="{% url 'core:delete' %}" style="text-decoration: none;">Excluir</a>
                                    </div>
                                </div>
                            {% else %}
                                <a href="{% url 'core:register' %}" style="text-decoration: none; color: inherit;">Cadastro</a>
                                <a href="{% url 'core:login' %}" style="text-decoration: none; color: inherit;">Login</a>
                            {% endif %}
                        </div>

                        <a href="{% url 'core:brainwave' %}" style="text-decoration: none; color: inherit;">
                            <img class="login_icon" src="{% static 'images/pessoa@2x.png' %}" alt="">
                        </a>
                    </div>
                </div>
            </div>

            <div class="corpo">
                <div class = "atuais">
                    <form class="novo_post" method="post" action="." enctype="multipart/form-data">
                        {% csrf_token %}

                        {{ form.titulo }}

                        {{ form.texto }}

                        {% if form.errors or form.non_field_errors %}
                        <div class="mb-3 p-6 bg-red-100 rounded-xl">
                            {% for field in form %}
                                {{ field.errors }}
                            {% endfor %}
                
                            {{ form.non_field_errors }}
                        </div>
                        {% endif %}

                        <button type="submit">
                            <img src="{% static 'images/enviar-1@2x.png' %}" alt="" style = "width: 50px; height: 47.4px;"> 
                        </button>
                    </form>
                </div>
            </div>  
        </div>
    </body>
</html>

post/templates/post.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="stylesheet" href="{% static 'css/post.css' %}" />
        <link rel="stylesheet" href="{% static 'css/index.css' %}" />
        <link rel="stylesheet" href="{% static 'css/global.css' %}" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Arial:ital,wght@0,400;1,400&display=swap"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,400;0,700;1,400&display=swap"/>
        <title>{% block title %}Post | Brainwave{% endblock %}</title>
    </head>
    
    <body>
        <div class = "body">
            <div>
                <img class = "onda_roxa" src="{% static 'images/onda-roxa@2x.png' %}" alt="">
                <img class = "mascote" src="{% static 'images/mascote@2x.png' %}" alt="">
                <img class = "logo" src="{% static 'images/logo@2x.png' %}" alt="">
                <em  class = "frase_efeito" >“Conectando mentes acadêmicas” - GRAN</em>
                <div class = "nome_empresa_1">Brainwave</div>
                <div class = "nome_empresa_2"><em>Network</em></div>
                <div class = "cabecalho">
                    <div class = "header_botao_1">
                        <a href="{% url 'core:brainwave' %}" style="text-decoration: none; color: inherit;"><img class = "home_icon"  src="{% static 'images/home@2x.png' %}" alt=""></a>
                        <div style="align-self: center; margin-left: 10px;"><a href="{% url 'core:brainwave' %}" style="text-decoration: none; color: inherit;">Início</a></div>
                    </div>
                    <a href="{% url 'post:new' %}" style="text-decoration: none; color: inherit;"><div class = "header_botao_2"><div class = "simbolo_mais">+</div></div></a>
                    <div class="header_botao_3">
                        <div style="align-self: center; margin-right: 10px;">
                        {% if request.user.is_authenticated %} 
                            <div class="dropdown">
                                <p href="javascript:void(0);" class="dropdown-toggle" style="text-decoration: none; margin-top: 20px;">{{ request.user.username }}</p>
                                <div class="dropdown-menu">
                                    <a href="{% url 'core:logout' %}" style="text-decoration: none;">Sair</a>
                                    <a href="{% url 'core:delete' %}" style="text-decoration: none;">Excluir</a>
                                </div>
                            </div>
                        {% else %}
                            <a href="{% url 'core:register' %}" style="text-decoration: none; color: inherit;">Cadastro</a>
                            <a href="{% url 'core:login' %}" style="text-decoration: none; color: inherit;">Login</a>
                        {% endif %}
                    </div>

                    <a href="{% url 'core:brainwave' %}" style="text-decoration: none; color: inherit;">
                        <img class="login_icon" src="{% static 'images/pessoa@2x.png' %}" alt="">
                    </a>
                </div>
            </div>


            <div class="corpo">
                <!-- <div class = "em_alta">
                    <h1 style="color: #ee00ff; font-size: 35pt; text-decoration: underline;">Em Alta</h1>
                    <ol>
                        {% for post in posts_by_likes %}
                            <a href="{% url 'post:detail' pk=post.id %}" style="text-decoration: underline; color: inherit; height: 58px; font-family: Lucida Console, monospace;">
                                <li style="margin-left: 40px; padding-top: 10px;">{{ post.titulo }}</li>
                            </a>
                        {% endfor %}
                    </ol>
                </div>-->
            

                <div class = "atuais">
                    <div class = "post">
                        <div class = "titulo">
                            <p style="text-decoration: none; color: #ee00ff; font-style: italic; font-family: Lucida Console, monospace; opacity: 0.9;">{{ post.created_by.username }}</p>
                            <h1 style="text-decoration: none; color: #ee00ff; font-weight: bold; font-family: Arial, Helvetica, sans-serif;">{{ post.titulo }}</h1>
                            {% if post.created_by == request.user %}
                            <form method="post" action="{% url 'post:delete' pk=post.id %}">
                                {% csrf_token %}
                                <button type="submit" class="delete-post-button" style="border: none; appearance: none; background-color: inherit;">
                                    <img src="{% static 'images/bin.png' %}" alt="Excluir">
                                </button>
                            </form>
                            {% endif %}
                        </div>



                        <p style="text-decoration: none; color: white;  text-align: justify; text-justify: inter-word; font-family: Lucida Console, monospace; opacity: 0.9;">{{ post.texto }}</p>

                        <form style="display: flex; justify-content: center; align-items: center; padding-top: 30px; gap: 10px;">
                            <p id="likes-count">{{ post.likes.count }}</p>
                            <button type="button" onclick="likePost({{ post.id }})" style="border: none; appearance: none; background-color: inherit;">
                                <img src="{% static 'images/brain-1@2x.png' %}" alt="" style="width: 50px; height: 47.4px;">
                            </button>
                        </form>
                    </div>
                    

                    <form class="novo_post" method="post" action="{% url 'post:post_detail' pk=post.id %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ comment_form.texto }}
                        <button type="submit">
                            <img src="{% static 'images/enviar-1@2x.png' %}" alt="" style = "width: 50px; height: 47.4px;"> 
                        </button>
                    </form>

                    {% for comment in comments %}
                    <div class="post_comment">
                        <div class="titulo">
                            <p style="text-decoration: none; color: #ee00ff; font-style: italic; font-family: Lucida Console, monospace; opacity: 0.9;">{{ comment.user.username }}</p>
                            {% if comment.user == request.user %}
                                <form method="post" action="{% url 'post:delete_comment' pk=comment.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="delete-comment-button" style="border: none; appearance: none; background-color: inherit;">
                                        <img src="{% static 'images/bin.png' %}" alt="Excluir">
                                    </button>
                                </form>
                            {% endif %}
                            <img src="{% static 'images/resposta-1-3@2x.png' %}" alt="" style="width: 60px;height: 50px;">
                        </div>
                        <p style="text-decoration: none; color: white; text-align: justify; text-justify: inter-word; font-family: Lucida Console, monospace; opacity: 0.9;">{{ comment.texto }}</p>
                        <div style="display: flex; justify-content: center; align-items: center; padding-top: 30px; gap: 10px;">
                            <p id="comment-likes-count-{{ comment.id }}">{{ comment.likes.count }}</p>
                            <button class="like-comment" onclick="likeComment({{ comment.id }})" style="border: none; appearance: none; background-color: inherit;">
                                <img src="{% static 'images/brain-1@2x.png' %}" alt="" style="width: 50px; height: 47.4px;">
                            </button>
                        </div>
                    </div>
                    {% endfor %}
                </div>
        </div>
    </body>
</html>

<script>
    function likePost(postId) {
        fetch(`/post/${postId}/like/`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}'
            },
            credentials: 'same-origin',
        })
        .then(response => response.json())
        .then(data => {
            const likesCountElement = document.getElementById('likes-count');
            likesCountElement.innerText = data.likes_count;
        })
        .catch(error => console.error('Error:', error));
    }

    function likeComment(commentId) {
        fetch(`/post/comment/${commentId}/like/`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}'
            },
            credentials: 'same-origin',
        })
        .then(response => response.json())
        .then(data => {
            const likesCountElement = document.getElementById(`comment-likes-count-${commentId}`);
            likesCountElement.innerText = data.likes_count;
        })
        .catch(error => console.error('Error:', error));
    }
</script>