brainwave/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('post/', include('post.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .views import logout_view, delete_account
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    
    path('register/', views.signup, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', logout_view, name='logout'),
    path('delete/', delete_account, name='delete'),
    path('brainwave/', views.brainwave, name='brainwave'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

post/urls.py
from django.urls import path

from . import views
from .views import post_detail

app_name = 'post'

urlpatterns = [
    path('', views.posts, name='posts'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/', post_detail, name='post_detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:post_id>/like/', views.like_post, name='like_post'),
    path('comment/<int:comment_id>/like/', views.like_comment, name='like_comment'),
    path('comment/<int:pk>/delete/', views.delete_comment, name='delete_comment'),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Nome de Usuário',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Senha',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Nome de Usuário',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'E-mail',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Senha',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirme senha',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from item.models import Category, Item
from django.db.models import Count
from post.models import Post
from .forms import SignupForm, LoginForm

def contact(request):
    return render(request, 'core/contact.html')

def brainwave(request):
    # Obtenha os posts ordenados pela contagem de curtidas (do maior para o menor)
    posts_by_likes = Post.objects.annotate(likes_count=Count('likes')).order_by('-likes_count')

    # Obtenha os posts ordenados pela data de criação (do mais recente para o mais antigo)
    posts_by_date = Post.objects.all().order_by('-created_at')

    # Renderize o template 'brainwave.html' com as duas listas de posts
    return render(request, 'core/brainwave.html', {'posts_by_likes': posts_by_likes, 'posts_by_date': posts_by_date})

def index(request):
    # Obtenha os posts ordenados pela contagem de curtidas (do maior para o menor)
    posts_by_likes = Post.objects.annotate(likes_count=Count('likes')).order_by('-likes_count')

    # Obtenha os posts ordenados pela data de criação (do mais recente para o mais antigo)
    posts_by_date = Post.objects.all().order_by('-created_at')

    # Renderize o template 'brainwave.html' com as duas listas de posts
    return render(request, 'core/brainwave.html', {'posts_by_likes': posts_by_likes, 'posts_by_date': posts_by_date})

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('core:login')

    else:
        form = SignupForm()

    return render(request, 'core/register.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('core:brainwave')
    
@login_required
def delete_account(request):
    # Excluir o usuário e desconectar
    request.user.delete()
    logout(request)
    return redirect('core:brainwave')  

core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | Puddle</title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">Puddle</a>

            <div class="space-x-6">
                <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>
                <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>
                <a href="{% url 'core:brainwave' %}" class="text-lg font-semibold hover:text-gray-500">Brainwave</a>

                {% if request.user.is_authenticated %}
                    <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                    <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                {% else %}
                    <a href="{% url 'core:register' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500">Lorem ipsum bla bla bla. Lorem ipsum bla bla bla. Lorem ipsum bla bla bla.</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

core/templates/core/brainwave.html
{% load static %}
<!DOCTYPE html>


<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="initial-scale=1, width=device-width">
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
        <link rel="stylesheet" href="{% static 'css/global.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Arial:ital,wght@0,400;1,400&display=swap">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,400;0,700;1,400&display=swap">
        <title>{% block title %}Página Inicial | Brainwave{% endblock %}</title>
    </head>

    <body>
        <div class = "body">
            <div>
                <img class = "onda_roxa" src="{% static 'images/onda-roxa@2x.png' %}" alt="">
                <img class = "mascote" src="{% static 'images/mascote@2x.png' %}" alt="">
                <img class = "logo" src="{% static 'images/logo@2x.png' %}" alt="">
                <em  class = "frase_efeito" >“Conectando mentes acadêmicas” - GRAN</em>
                <div class = "nome_empresa_1">Brainwave</div>
                <div class = "nome_empresa_2"><em>Network</em></div>

                
                <div class = "cabecalho">
                    <div class = "header_botao_1">
                        <a href="" style="text-decoration: none; color: inherit;"><img class = "home_icon"  src="{% static 'images/home@2x.png' %}" alt=""></a>
                        
                        <div style="align-self: center; margin-left: 10px;"><a href="" style="text-decoration: none; color: inherit;">Início</a></div>
                    </div>
                    <a href="{% url 'post:new' %}" style="text-decoration: none; color: inherit;"><div class = "header_botao_2"><div class = "simbolo_mais">+</div></div></a>

                    <div class="header_botao_3">
                        <div style="align-self: center; margin-right: 10px;">
                            {% if request.user.is_authenticated %} 
                                <div class="dropdown">
                                    <p href="javascript:void(0);" class="dropdown-toggle" style="text-decoration: none; margin-top: 20px;">{{ request.user.username }}</p>
                                    <div class="dropdown-menu">
                                        <a href="{% url 'core:logout' %}" style="text-decoration: none;">Sair</a>
                                        <a href="{% url 'core:delete' %}" style="text-decoration: none;">Excluir</a>
                                    </div>
                                </div>
                            {% else %}
                                <a href="{% url 'core:register' %}" style="text-decoration: none; color: inherit;">Cadastro</a>
                                <a href="{% url 'core:login' %}" style="text-decoration: none; color: inherit;">Login</a>
                            {% endif %}
                        </div>

                        <a href="{% url 'core:brainwave' %}" style="text-decoration: none; color: inherit;">
                            <img class="login_icon" src="{% static 'images/pessoa@2x.png' %}" alt="">
                        </a>
                    </div>
                </div>
            </div>
            
            <div class = "corpo">
                <div class = "em_alta">
                    <h1 style="color: #ee00ff; font-size: 35pt; text-decoration: underline;">Em Alta</h1>
                    <ol>
                        {% for post in posts_by_likes %}
                            <a href="{% url 'post:detail' pk=post.id %}" style="text-decoration: underline; color: inherit; height: 58px; font-family: Lucida Console, monospace;">
                                <li style="margin-left: 40px; padding-top: 10px;">{{ post.titulo }}</li>
                            </a>
                        {% endfor %}
                    </ol>
                </div>

                <div class="atuais">
                    {% for post in posts_by_date %}
                        <div class="post">
                            <div class="titulo">
                                <p style="text-decoration: none; color: #ee00ff; font-style: italic; font-family: Lucida Console, monospace; opacity: 0.9;">{{ post.created_by.username }}</p>
                                <a style="text-decoration: none; color: #ee00ff; font-weight: bold; font-family: Arial, Helvetica, sans-serif;" href="{% url 'post:detail' pk=post.id %}">
                                    <h1>{{ post.titulo }}</h1>
                                </a>
                            </div>
                            <p style="text-decoration: none; color: white; text-align: justify; text-justify: inter-word; font-family: Lucida Console, monospace; opacity: 0.9;">{{ post.texto }}</p>
                            <div class="img_post">
                                <form style="display: flex; justify-content: center; align-items: center; padding-top: 30px; gap: 10px;">
                                    <!-- Use o ID diretamente para a contagem de curtidas -->
                                <p id="likes-count-{{ post.id }}">{{ post.likes.count }}</p>
                                <button type="button" onclick="likePost({{ post.id }})" style="border: none; appearance: none; background-color: inherit;">
                                    <img src="{% static 'images/brain-1@2x.png' %}" alt="" style="width: 50px; height: 47.4px;">
                                </button>
                                </form>
                                <a href="{% url 'post:detail' pk=post.id %}" style="text-decoration: none; color: inherit; height: 58px;">
                                    <img src="{% static 'images/speechbubble-1-1@2x.png' %}" alt="" style="width: 61px; height: 58px;">
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>

            </div>
        </div>
    </body>
</html>

<script>
    function likePost(postId) {
        fetch(`/post/${postId}/like/`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}'
            },
            credentials: 'same-origin',
        })
        .then(response => response.json())
        .then(data => {
            // Use o ID diretamente para atualizar a contagem de curtidas
            const likesCountElement = document.getElementById(`likes-count-${postId}`);
            likesCountElement.innerText = data.likes_count;
        })
        .catch(error => console.error('Error:', error));
    }
</script>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="#">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div> 

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
            <div>
                <a href="#">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">{{ category.items.count }} items</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/logcad.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="stylesheet" href="{% static 'css/login.css' %}" />
        <link rel="stylesheet" href="{% static 'css/index.css' %}" />
        <link rel="stylesheet" href="{% static 'css/global.css' %}" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Arial:ital,wght@0,400;1,400&display=swap">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,400;0,700;1,400&display=swap">
    </head>


    <body>
        <div class = "body">
            <div>
                <img class = "onda_roxa" src="{% static 'images/onda-roxa@2x.png' %}" alt="">
                <img class = "mascote" src="{% static 'images/mascote@2x.png' %}" alt="">
                <img class = "logo" src="{% static 'images/logo@2x.png' %}" alt="">
                <em  class = "frase_efeito" >“Conectando mentes acadêmicas” - GRAN</em>
                <div class = "nome_empresa_1">Brainwave</div>
                <div class = "nome_empresa_2"><em>Network</em></div>
                <div class = "cabecalho" >
                    <div class = "header_botao_1">
                        <a href="{% url 'core:brainwave' %}" style="text-decoration: none; color: inherit;"><img class = "home_icon"  src="{% static 'images/home@2x.png' %}" alt=""></a>
                        
                        <div style="align-self: center; margin-left: 10px;"><a href="{% url 'core:brainwave' %}" style="text-decoration: none; color: inherit;">Início</a></div>
                    </div>
                    <a href="../pgs/create_post.html" style="text-decoration: none; color: inherit;"><div class = "header_botao_2"><div class = "simbolo_mais">+</div></div></a>
                    <div class = "header_botao_3"><div style="align-self: center; margin-right: 10px;"><a href="" style="text-decoration: none; color: inherit;">Login/Cadastro</a></div><a href="" style="text-decoration: none; color: inherit;"><img class = "login_icon" src="{% static 'images/pessoa@2x.png' %}" alt=""></a></div>
                </div>
            </div>

            <div>
                <div style="display: flex; justify-content: space-around;">
                    <div class = "cadastro">
                        <form method="post" action=".">
                            {% csrf_token %}

                            <h1>Cadastro</h1>
                            {{ form.email }}

                            {{ form.username }}

                            {{ form.password1 }}

                            {{ form.password2 }}

                            {% if form.errors or form.non_field_errors %}
                                <div class="error-container">
                                    {% for field in form %}
                                        {{ field.errors }}
                                    {% endfor %}
                    
                                    {{ form.non_field_errors }}
                    
                                </div>
                            {% endif %}

                            <button type="submit" value="Submit">Cadastrar</button>
                        </form>
                    </div>

                    <div class = "login">
                        <form method="post" action=".">
                            <h1>Log In</h1>
                            {{ form.email }}

                            {{ form.password1 }}    

                            <button type="submit" value="Submit">Logar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

core/templates/core/login.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="stylesheet" href="{% static 'css/login.css' %}" />
        <link rel="stylesheet" href="{% static 'css/index.css' %}" />
        <link rel="stylesheet" href="{% static 'css/global.css' %}" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Arial:ital,wght@0,400;1,400&display=swap">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,400;0,700;1,400&display=swap">
        <title>{% block title %}Login | Brainwave{% endblock %}</title>
    </head>


    <body>
        <div class = "body">
            <div>
                <img class = "onda_roxa" src="{% static 'images/onda-roxa@2x.png' %}" alt="">
                <img class = "mascote" src="{% static 'images/mascote@2x.png' %}" alt="">
                <img class = "logo" src="{% static 'images/logo@2x.png' %}" alt="">
                <em  class = "frase_efeito" >“Conectando mentes acadêmicas” - GRAN</em>
                <div class = "nome_empresa_1">Brainwave</div>
                <div class = "nome_empresa_2"><em>Network</em></div>
                
                <div class = "cabecalho">
                    <div class = "header_botao_1">
                        <a href="{% url 'core:brainwave' %}" style="text-decoration: none; color: inherit;"><img class = "home_icon"  src="{% static 'images/home@2x.png' %}" alt=""></a>
                        
                        <div style="align-self: center; margin-left: 10px;"><a href="{% url 'core:brainwave' %}" style="text-decoration: none; color: inherit;">Início</a></div>
                    </div>
                    <a href="{% url 'post:new' %}" style="text-decoration: none; color: inherit;"><div class = "header_botao_2"><div class = "simbolo_mais">+</div></div></a>

                    <div class="header_botao_3">
                        <div style="align-self: center; margin-right: 10px;">
                            {% if request.user.is_authenticated %} 
                                <div class="dropdown">
                                    <p href="javascript:void(0);" class="dropdown-toggle" style="text-decoration: none; margin-top: 20px;">{{ request.user.username }}</p>
                                    <div class="dropdown-menu">
                                        <a href="{% url 'core:logout' %}" style="text-decoration: none;">Sair</a>
                                        <a href="" style="text-decoration: none;">Excluir</a>
                                    </div>
                                </div>
                            {% else %}
                                <a href="{% url 'core:register' %}" style="text-decoration: none; color: inherit;">Cadastro</a>
                                <a href="{% url 'core:login' %}" style="text-decoration: none; color: inherit;">Login</a>
                            {% endif %}
                        </div>

                        <a href="{% url 'core:brainwave' %}" style="text-decoration: none; color: inherit;">
                            <img class="login_icon" src="{% static 'images/pessoa@2x.png' %}" alt="">
                        </a>
                    </div>
                </div>
            </div>


            <div>
                <div style="display: flex; justify-content: space-around;">
                    <div class = "login">
                        <form method="post" action=".">
                            {% csrf_token %}

                            <h1>Log In</h1>
                            {{ form.username }}

                            {{ form.password }}  
                            

                            {% if form.errors or form.non_field_errors %}
                                <div class="error-container">
                                    {% for field in form %}
                                        {{ field.errors }}
                                    {% endfor %}
                                    {{ form.non_field_errors }}
                                </div>
                            {% endif %}

                            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Logar</button>
                            <br/>
                            <br/>
                            <p style="color: #ee00ff;">Não possui uma conta? <a href="{% url 'core:register' %}">Registre-se</a>.</p>
                        </form>
                    </div>
                </div>
            </div>
            
        </div>
    </body>
</html>

core/templates/core/register.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="stylesheet" href="{% static 'css/login.css' %}" />
        <link rel="stylesheet" href="{% static 'css/index.css' %}" />
        <link rel="stylesheet" href="{% static 'css/global.css' %}" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Arial:ital,wght@0,400;1,400&display=swap">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,400;0,700;1,400&display=swap">
        <title>{% block title %}Cadastro | Brainwave{% endblock %}</title>
    </head>


    <body>
        <div class = "body">
            <div>
                <img class = "onda_roxa" src="{% static 'images/onda-roxa@2x.png' %}" alt="">
                <img class = "mascote" src="{% static 'images/mascote@2x.png' %}" alt="">
                <img class = "logo" src="{% static 'images/logo@2x.png' %}" alt="">
                <em  class = "frase_efeito" >“Conectando mentes acadêmicas” - GRAN</em>
                <div class = "nome_empresa_1">Brainwave</div>
                <div class = "nome_empresa_2"><em>Network</em></div>
                
                <div class = "cabecalho">
                    <div class = "header_botao_1">
                        <a href="{% url 'core:brainwave' %}" style="text-decoration: none; color: inherit;"><img class = "home_icon"  src="{% static 'images/home@2x.png' %}" alt=""></a>
                        
                        <div style="align-self: center; margin-left: 10px;"><a href="{% url 'core:brainwave' %}" style="text-decoration: none; color: inherit;">Início</a></div>
                    </div>
                    <a href="./pgs/create_post.html" style="text-decoration: none; color: inherit;"><div class = "header_botao_2"><div class = "simbolo_mais">+</div></div></a>

                    <div class="header_botao_3">
                        <div style="align-self: center; margin-right: 10px;">
                            {% if request.user.is_authenticated %} 
                                <div class="dropdown">
                                    <p href="javascript:void(0);" class="dropdown-toggle" style="text-decoration: none; margin-top: 20px;">{{ request.user.username }}</p>
                                    <div class="dropdown-menu">
                                        <a href="{% url 'core:logout' %}" style="text-decoration: none;">Sair</a>
                                        <a href="" style="text-decoration: none;">Excluir</a>
                                    </div>
                                </div>
                            {% else %}
                                <a href="{% url 'core:register' %}" style="text-decoration: none; color: inherit;">Cadastro</a>
                                <a href="{% url 'core:login' %}" style="text-decoration: none; color: inherit;">Login</a>
                            {% endif %}
                        </div>

                        <a href="{% url 'core:brainwave' %}" style="text-decoration: none; color: inherit;">
                            <img class="login_icon" src="{% static 'images/pessoa@2x.png' %}" alt="">
                        </a>
                    </div>
                </div>
            </div>


            
            <div>
                <div style="display: flex; justify-content: space-around;">
                    <div class = "cadastro">
                        <form method="post" action="{% url 'core:register' %}">
                            {% csrf_token %}

                            <h1>Cadastro</h1>
                            {{ form.email }}

                            {{ form.username }}

                            {{ form.password1 }}

                            {{ form.password2 }}

                            {% if form.errors or form.non_field_errors %}
                                <div class="error-container">
                                    {% for field in form %}
                                        {{ field.errors }}
                                    {% endfor %}
                    
                                    {{ form.non_field_errors }}
                    
                                </div>
                            {% endif %}

                            <button type="submit" value="Submit">Cadastrar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>